### ISSUE TITLE
ImportError: No module named 'fs'

### ISSUE THREAD

**Issue by SeekPoint** [MehdiAB161/Autoencoder-Stability#2]
rzai@rzai00:~/prj/Neural-Networks-for-Collaborative-Filtering$ python3 main.py
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so locally
/usr/local/lib/python3.4/dist-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from config.stability.V_1M import Experiment
  File "/home/rzai/prj/Neural-Networks-for-Collaborative-Filtering/config/stability/V_1M.py", line 1, in <module>
    from stability.ExperimentStability import ExperimentStability
  File "/home/rzai/prj/Neural-Networks-for-Collaborative-Filtering/stability/ExperimentStability.py", line 1, in <module>
    from autoencoder.Experiment import Experiment
  File "/home/rzai/prj/Neural-Networks-for-Collaborative-Filtering/autoencoder/Experiment.py", line 5, in <module>
    from autoencoder.Import import Import
  File "/home/rzai/prj/Neural-Networks-for-Collaborative-Filtering/autoencoder/Import.py", line 5, in <module>
    from tools.tools import global_parameters
  File "/home/rzai/prj/Neural-Networks-for-Collaborative-Filtering/tools/tools.py", line 1, in <module>
    from fs.osfs import OSFS
ImportError: No module named 'fs'
rzai@rzai00:~/prj/Neural-Networks-for-Collaborative-Filtering$

**Comment by MehdiAbbanaBennani** [comment]
You can install the PyFilesystem module with pip as follows :
`pip install fs`

**Comment by SeekPoint** [comment]
fixed
